[settings]
max_concurrent_challenges = 2
max_actions_per_minute = 5

[discord]
client_id = "1248440441649500243"
client_secret = "5j2OiR-OJks6q56ek1zCxJg4s68SITZd"
redirect_url = "http://127.0.0.1:3000/login"
server_id = "728386362625097779"

[database]
file_path = "database.db"

[deployers.file]
path = "./deployment-scripts/deploy-file.sh"

[deployers.incus]
path = "./deployment-scripts/deploy-incus.sh"

[challenges.my-challenge-1]
name = "Un certain défi"
description = "Avec des détails de déploiement quelconques..."
ttl = "1m"
deployer = "file"

[challenges.my-challenge-2]
name = "Un certain défi 2"
description = "Avec des détails de déploiement quelconques..."
ttl = "1m"
deployer = "file"

[challenges.web-1]
name = "Nginx 🎡"
ttl = "5m"
deployer = "incus"