[settings]
max_concurrent_challenges = 2

[discord]
client_id = "1248440441649500243"
client_secret = "5j2OiR-OJks6q56ek1zCxJg4s68SITZd"
redirect_url = "http://127.0.0.1:3000/login"
server_id = "728386362625097779"

[database]
file_path = "database.db"

[deployers.docker-stack]
path = "./deployment-scripts/deploy-docker-stack.sh"

[deployers.file]
path = "./deployment-scripts/deploy-file.sh"

[challenges.my-challenge-1]
name = "Mon super défi"
description = "Un challenge qui a vraiment beaucoup de contenu, bonne chance!"
ttl = "15m"
deployer = "docker-stack"

[challenges.my-challenge-2]
name = "Mon super défi, la suite"
ttl = "10m"
deployer = "docker-stack"

[challenges.my-challenge-3]
name = "Défi bizarre"
ttl = "1m"
deployer = "file"